#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --job-name=nn_approx                    ### Job name 
#SBATCH --partition main			### specify partition name where to run a job. main: all nodes; gtx1080: 1080 gpu card nodes; rtx2080: 2080 nodes; teslap100: p100 nodes; titanrtx: titan nodes
#SBATCH --output %x-%J.out          		### output log for running job - %J for job number
#SBATCH --mem=60G			     	### ammount of RAM memory, allocating more than 60G requires IT team's permission


### Note: the following 4 lines are commented out
##SBATCH --time 3-20:00:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --gpus=1				### number of GPUs, allocating more than 1 requires IT team's permission
##SBATCH --mail-user=user@post.bgu.ac.il	### user's email for sending job status messages
##SBATCH --mail-type=ALL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE

################  Following lines will be executed by a compute node    #######################

### Print some data to output file ###
echo Starting at: `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"
echo -e $JOB_NAME


### Start your code below ####
module load anaconda				  ### load anaconda module (must be present when working with conda environments)
source activate my_env				  ### activate a conda environment, replace my_env with your conda environment
python lifted_nsb_using_funct_fitting.py
echo Ended at: `date`
